language: php
php:
  - '5.4'
  - '5.5'
  - '5.5.9'
  - '5.6'
  - '7.0'
  - hhvm
matrix:
  allow_failures:
    - php: '5.4'
    - php: '7.0'
    - php: hhvm
install:
  - if [[ "$(phpenv version-name)" != "hhvm" ]]; then echo 'error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - composer install $(ver="$(phpenv version-name)"; if [[ "${ver:0:3}" == "5.5" || "${ver:0:3}" == "5.4" ]]; then echo '--ignore-platform-reqs'; fi)
script:
  - php vendor/bin/behat --config=.travis-behat.yml
  - php vendor/bin/phpspec run -v --config=.travis-phpspec.yml
  - phpunit -v --color -c .travis-phpunit.xml
